Repository astrocamp/14th-JoBand, pull requests merged in 2023-08, with the labels that each got.

#8 style: 登入/註冊＆navbar 畫面切版 （附加：中英語內容yml)
  app/assets/stylesheets/application.tailwind.css
  app/views/layouts/application.html.erb
  app/views/pages/index.html.erb
  app/views/shared/_flash.html.erb
  app/views/shared/_navbar.html.erb
  app/views/users/registrations/new.html.erb
  app/views/users/sessions/new.html.erb
  app/views/users/shared/_links.html.erb
  config/locales/en.yml
  config/locales/tw.yml
  config/tailwind.config.js
Labels: enhancement

#9 新增Google & Facebook 第三方登入 feat: add OAuth -login
  .env.sample
  .gitignore
  .vscode/settings.json
  Gemfile
  Gemfile.lock
  app/controllers/Users/omniauth_callbacks_controller.rb
  app/models/user.rb
  config/initializers/devise.rb
  config/routes.rb
  db/migrate/20230811025201_add_omniauth_to_users.rb
  db/schema.rb
Labels: enhancement

#10 feat: 新增 email 認證功能、重發認證信，客製化認證 email 頁面 (附 i18n 中/英文)
  .env.sample
  .gitignore
  Gemfile
  Gemfile.lock
  app/controllers/Users/confirmations_controller.rb
  app/mailers/user_mailer.rb
  app/models/user.rb
  app/views/user_mailer/confirmation_instructions.html.erb
  app/views/users/confirmations/new.html.erb
  app/views/users/shared/_links.html.erb
  config/environments/development.rb
  config/initializers/devise.rb
  config/locales/en.yml
  config/locales/tw.yml
  config/routes.rb
  db/migrate/20230812152932_add_confirmable_to_devise.rb
  db/schema.rb
  spec/mailers/previews/user_preview.rb
  spec/mailers/user_spec.rb
Labels: enhancement

#12 feat: Band 創建樂團功能
  .env.sample
  Gemfile
  Gemfile.lock
  app/controllers/bands_controller.rb
  app/helpers/bands_helper.rb
  app/models/band.rb
  app/models/band_style.rb
  app/models/style.rb
  app/views/bands/_form.html.erb
  app/views/bands/_style.html.erb
  app/views/bands/edit.html.erb
  app/views/bands/index.html.erb
  app/views/bands/new.html.erb
  app/views/bands/show.html.erb
  app/views/shared/_navbar.html.erb
  config/routes.rb
  db/migrate/20230805101630_create_bands.rb
  db/migrate/20230812062952_create_styles.rb
  db/migrate/20230812063037_create_band_styles.rb
  db/schema.rb
  db/seeds.rb
  test/application_system_test_case.rb
  test/channels/application_cable/connection_test.rb
  test/controllers/.keep
  test/controllers/pages_controller_test.rb
  test/fixtures/files/.keep
  test/fixtures/users.yml
  test/helpers/.keep
  test/integration/.keep
  test/mailers/.keep
  test/models/.keep
  test/models/user_test.rb
  test/system/.keep
  test/test_helper.rb
Labels: enhancement

#13 feat: 新增 忘記密碼 email 發送、重設密碼，客製化 email 頁面 (附 i18n 中/英文)
  app/mailers/user_mailer.rb
  app/views/user_mailer/reset_password_instructions.html.erb
  app/views/users/passwords/edit.html.erb
  app/views/users/passwords/new.html.erb
  config/locales/en.yml
  config/locales/tw.yml
Labels: enhancement

#24 feat: 新增樂團大頭avatar 以及 banner 功能並在show & index頁面顯示
  Gemfile
  app/controllers/bands_controller.rb
  app/helpers/bands_helper.rb
  app/mailers/user_mailer.rb
  app/models/band.rb
  app/models/band_style.rb
  app/models/style.rb
  app/views/bands/_form.html.erb
  app/views/bands/index.html.erb
  app/views/bands/show.html.erb
  app/views/profiles/index.html.erb
  app/views/profiles/show.html.erb
  app/views/shared/_avatar.html.erb
  app/views/shared/_banner.html.erb
  config/routes.rb
  db/migrate/20230805101630_create_bands.rb
  db/migrate/20230812062952_create_styles.rb
  db/migrate/20230812063037_create_band_styles.rb
  db/schema.rb
  db/seeds.rb
  public/default_banner.jpg
Labels: 增加功能

#25 style: Band's CSS ( show, new, edit, index )
  Gemfile.lock
  app/assets/stylesheets/Band.css
  app/assets/stylesheets/actiontext.css
  app/assets/stylesheets/application.tailwind.css
  app/controllers/application_controller.rb
  app/controllers/bands_controller.rb
  app/javascript/application.js
  app/models/band.rb
  app/views/active_storage/blobs/_blob.html.erb
  app/views/bands/_band_cards.html.erb
  app/views/bands/_form.html.erb
  app/views/bands/_style.html.erb
  app/views/bands/edit.html.erb
  app/views/bands/index.html.erb
  app/views/bands/new.html.erb
  app/views/bands/show.html.erb
  app/views/layouts/action_text/contents/_content.html.erb
  app/views/shared/_navbar.html.erb
  config/importmap.rb
  config/locales/en.yml
  config/locales/tw.yml
  db/migrate/20230814100843_create_action_text_tables.action_text.rb
  db/schema.rb
  spec/models/band_member_spec.rb
Labels: 切版

#28 Feat : 新增 Profile 上傳音樂 / show 頁面會有音樂
  app/controllers/profiles_controller.rb
  app/models/profile.rb
  app/views/profiles/_form.html.erb
  app/views/profiles/index.html.erb
  app/views/profiles/show.html.erb
Labels: 增加功能

#30 feat: 加入 User model 跟 Profile 的關聯性
  .gitignore
  Gemfile
  Gemfile.lock
  app/assets/stylesheets/application.tailwind.css
  app/controllers/Users/registrations_controller.rb
  app/controllers/application_controller.rb
  app/controllers/profiles_controller.rb
  app/mailers/application_mailer.rb
  app/models/profile.rb
  app/models/user.rb
  app/policies/application_policy.rb
  app/views/pages/index.html.erb
  app/views/profiles/_form.html.erb
  app/views/profiles/edit.html.erb
  app/views/profiles/index.html.erb
  app/views/profiles/new.html.erb
  app/views/profiles/show.html.erb
  app/views/shared/_navbar.html.erb
  app/views/user_mailer/confirmation_instructions.html.erb
  app/views/user_mailer/reset_password_instructions.html.erb
  app/views/users/registrations/edit.html.erb
  app/views/users/registrations/new.html.erb
  app/views/users/sessions/new.html.erb
  config/locales/en.yml
  config/locales/tw.yml
  config/routes.rb
  config/tailwind.config.js
  db/migrate/20230817094350_add_user_relation_with.rb
  db/migrate/20230817120153_add_user_name_to_null_false.rb
  db/schema.rb
Labels: 增加功能

#34 fix: 修復先前的誤刪，加回 音樂 跟 影片欄位
  app/views/profiles/_form.html.erb
Labels: 更新文檔

#33 feat:創建Recruit及Recrui與Instrument的第三方表格,並Rubocop處理完畢,檔案修正完
  Gemfile.lock
  app/controllers/application_controller.rb
  app/controllers/profiles_controller.rb
  app/controllers/recruits_controller.rb
  app/helpers/recruits_helper.rb
  app/models/band.rb
  app/models/instrument.rb
  app/models/recruit.rb
  app/models/recruit_and_instrument.rb
  app/views/recruits/_form.html.erb
  app/views/recruits/edit.html.erb
  app/views/recruits/index.html.erb
  app/views/recruits/new.html.erb
  app/views/recruits/show.html.erb
  config/routes.rb
  db/migrate/20230814041042_create_recruits.rb
  db/migrate/20230816064608_remove_instrument_from_recruits.rb
  db/migrate/20230816065303_create_recruit_and_instruments.rb
  db/migrate/20230819161600_add_band_id_to_recruits.rb
  db/schema.rb
  spec/models/band_member_spec.rb
Labels: 增加功能

#38 Feat: 建立 User 跟 Band 多對多關聯
  .rubocop.yml
  app/controllers/application_controller.rb
  app/controllers/bands_controller.rb
  app/controllers/recruits_controller.rb
  app/helpers/bands_helper.rb
  app/helpers/profiles_helper.rb
  app/models/band.rb
  app/models/band_member.rb
  app/models/profile.rb
  app/models/user.rb
  app/views/bands/_band.html.erb
  app/views/bands/_form.html.erb
  app/views/bands/_member.html.erb
  app/views/bands/index.html.erb
  app/views/bands/show.html.erb
  app/views/profiles/_band.html.erb
  app/views/profiles/_form.html.erb
  app/views/profiles/_profile.html.erb
  app/views/profiles/index.html.erb
  app/views/profiles/show.html.erb
  db/migrate/20230822085424_create_band_members.rb
  db/schema.rb
Labels: 關聯性

#39 Feat: 搜尋樂手功能
  app/controllers/profiles_controller.rb
  app/models/band_member.rb
  app/models/instrument.rb
  app/models/profile.rb
  app/models/user.rb
  app/views/bands/index.html.erb
  app/views/profiles/index.html.erb
  app/views/profiles/show.html.erb
Labels: 增加功能

#44 Style: add oauth btn CSS 新增第三方登入外觀
  app/models/user.rb
  app/views/users/shared/_links.html.erb
Labels: 切版

#46 feat:新增Recruit associate分支 主要設置recruit與band之間的1對1關係
  Gemfile
  Gemfile.lock
  app/controllers/recruits_controller.rb
  app/helpers/application_helper.rb
  app/models/band.rb
  app/models/band_member.rb
  app/models/recruit.rb
  app/views/recruits/_form.html.erb
  app/views/recruits/index.html.erb
  app/views/recruits/new.html.erb
  app/views/recruits/show.html.erb
  config/routes.rb
Labels: 關聯性

#47 Feat: Band 增加 職位 的欄位
  app/controllers/bands_controller.rb
  app/models/band_member.rb
  app/views/bands/_form.html.erb
  app/views/bands/_member.html.erb
  db/migrate/20230824070202_change_band_members_columns.rb
  db/schema.rb
Labels: 增加功能

#57 style: 加上 網站小圖示 favicon
  app/assets/images/favicon.ico
  app/views/layouts/application.html.erb
Labels: 其他功能

#60 fix: fix the typo of current_user can't find the correct profile
  app/views/profiles/show.html.erb
  app/views/shared/_navbar.html.erb
Labels: 有bug, 更新文檔

#73 fix: profile update and change the type of phone to string
  app/controllers/profiles_controller.rb
  db/migrate/20230829043256_change_profile_tel_type_to_string.rb
  db/seeds.rb
Labels: 修 bug, 更新文檔, 急件先過！

#70 Feat: modify the flash with sweetalert2
  app/assets/stylesheets/application.css
  app/javascript/application.js
  app/javascript/controllers/flash_controller.js
  app/views/layouts/application.html.erb
  app/views/layouts/home.html.erb
  app/views/shared/_flash.html.erb
  config/importmap.rb
Labels: 其他功能, 急件先過！

#75 Chore & style: 加入 authenticate user, 修改 profile、band 部分 view 的 按鈕 及 色調一致性，修正 i18n 部份錯誤
  app/controllers/bands_controller.rb
  app/controllers/profiles_controller.rb
  app/controllers/recruits_controller.rb
  app/controllers/users/confirmations_controller.rb
  app/controllers/users/registrations_controller.rb
  app/models/user.rb
  app/views/bands/_band.html.erb
  app/views/bands/_form.html.erb
  app/views/bands/new.html.erb
  app/views/bands/show.html.erb
  app/views/profiles/index.html.erb
  app/views/profiles/show.html.erb
  app/views/profiles/welcome.html.erb
  app/views/shared/_navbar.html.erb
  app/views/users/confirmations/new.html.erb
  app/views/users/registrations/edit.html.erb
  app/views/users/registrations/new.html.erb
  config/application.rb
  config/initializers/devise.rb
  config/locales/en.yml
  config/locales/tw.yml
  config/routes.rb
  public/Joband_logo.png
  public/Joband_logo_black.png
  public/Joband_logo_black.svg
Labels: 切版, 重構程式碼

#77 fix: fix typo
  app/views/bands/_band.html.erb
  app/views/bands/_form.html.erb
Labels: 修 bug, 急件先過！

#79 Refactor: 重構程式碼，不影響功能，只是改進程式碼結構＆可讀性。
  Gemfile
  app/controllers/users/omniauth_callbacks_controller.rb
  app/models/user.rb
  app/views/users/shared/_links.html.erb
  config/initializers/devise.rb
  db/migrate/20230829083949_remove_oauth_from_users.rb
  db/migrate/20230829084108_add_oauth_to_users.rb
Labels: 急件先過！, 重構程式碼

#82 Feat : 將檔案利用 Amazon s3 服務上傳成功
  .env.sample
  Gemfile
  Gemfile.lock
  config/environments/development.rb
  config/storage.yml
Labels: 增加功能
