Repository astrocamp/14th-JoBand, pull requests merged in 2023-09, with the labels that each got.

#83 Docs: db:seed 大禮包，會員添加免註冊，I18n 樂器、樂手
  Gemfile
  Gemfile.lock
  app/models/user.rb
  config/locales/devise.en.yml
  config/locales/en.yml
  config/locales/tw.yml
  db/seeds.rb
Labels: 更新文檔

#105 Feat: 樂團申請 的 編輯功能
  app/controllers/resume_lists_controller.rb
  app/models/recruit.rb
  app/views/resume_lists/show.html.erb
Labels: 增加功能

#108 Feat : activity CRUD + 活動的 banner 成功上傳至 Amazon S3
  app/controllers/activities_controller.rb
  app/helpers/activities_helper.rb
  app/models/activity.rb
  app/views/activities/_activity.html.erb
  app/views/activities/_form.html.erb
  app/views/activities/edit.html.erb
  app/views/activities/index.html.erb
  app/views/activities/new.html.erb
  app/views/activities/show.html.erb
  app/views/bands/show.html.erb
  app/views/shared/_activityBanner.html.erb
  app/views/shared/_banner.html.erb
  config/routes.rb
  db/migrate/20230901024732_create_activities.rb
  db/schema.rb
  public/default_activityBanner.jpg
Labels: 增加功能, 急件先過！

#109 fix: 樂器 svg 改名為中文
  public/icon_img/主唱.svg
  public/icon_img/吉他.svg
  public/icon_img/爵士鼓.svg
  public/icon_img/貝斯.svg
  public/icon_img/鍵盤.svg
Labels: bug, 更新文檔

#110 feat: 貼文 的 CRD 與 user 關聯性, 可互動中
  Gemfile
  app/assets/images/icon/comment.svg
  app/assets/images/icon/del.svg
  app/assets/images/icon/home.svg
  app/assets/images/icon/like.svg
  app/assets/images/icon/liked.svg
  app/assets/images/icon/play.svg
  app/assets/images/icon/plus.svg
  app/assets/images/icon/profile.svg
  app/controllers/activities_controller.rb
  app/controllers/posts_controller.rb
  app/javascript/controllers/index.js
  app/javascript/controllers/reset_form_controller.js
  app/models/activity.rb
  app/models/post.rb
  app/models/user.rb
  app/views/posts/_empty.html.erb
  app/views/posts/_new.html.erb
  app/views/posts/index.html.erb
  app/views/shared/_navbar.html.erb
  app/views/users/passwords/edit.html.erb
  config/locales/en.yml
  config/locales/tw.yml
  config/routes.rb
  db/migrate/20230901034923_create_posts.rb
  db/schema.rb
Labels: 增加功能

#120 RWD root profile & profile card & band card & navbar
  app/assets/stylesheets/application.tailwind.css
  app/views/bands/_band.html.erb
  app/views/bands/_recruit.html.erb
  app/views/bands/_style.html.erb
  app/views/pages/index.html.erb
  app/views/profiles/_profile.html.erb
  app/views/profiles/index.html.erb
  app/views/shared/_instrument.html.erb
  app/views/shared/_instrument_search.html.erb
  app/views/shared/_navbar.html.erb
  config/tailwind.config.js
  db/schema.rb
  public/icon_img/dark.svg
  public/icon_img/light.svg
Labels: 切版, 急件先過！

#125 fix: hot fix resume list
  app/views/resume_lists/_form.html.erb
Labels: bug

#115 feat: 新增樂團及活動的關聯性,追加城市表格及activity_index頁面
  app/controllers/activities_controller.rb
  app/models/activity.rb
  app/models/band.rb
  app/views/activities/_activity.html.erb
  app/views/activities/_form.html.erb
  app/views/activities/activity_index.html.erb
  app/views/activities/index.html.erb
  app/views/activities/new.html.erb
  app/views/activities/show.html.erb
  app/views/bands/show.html.erb
  app/views/shared/_navbar.html.erb
  config/routes.rb
  db/migrate/20230903082757_add_band_id_to_activities.rb
  db/schema.rb
Labels: 關聯性, 急件先過！

#127 更加強調 light mode
  app/assets/stylesheets/application.css
  app/assets/stylesheets/application.tailwind.css
  app/views/pages/index.html.erb
  app/views/shared/_footer.html.erb
  app/views/shared/_navbar.html.erb
  public/icon_img/light.svg
Labels: 切版

#136 Hot fix : 為了上午的 Demo, 先從大ＰＲ中，獨立出來
  app/controllers/profiles_controller.rb
  app/models/band.rb
  app/policies/application_policy.rb
  app/policies/profile_policy.rb
Labels: bug, 急件先過！

#130 feat:增加活動搜尋功能
  app/controllers/activities_controller.rb
  app/models/activity.rb
  app/views/activities/activity_index.html.erb
  app/views/activities/index.html.erb
Labels: 增加功能

#134 Feat: 招募和申請的權限
  Gemfile.lock
  app/controllers/comments_controller.rb
  app/controllers/recruits_controller.rb
  app/controllers/resume_lists_controller.rb
  app/models/band.rb
  app/policies/recruit_policy.rb
  app/policies/resume_list_policy.rb
  app/views/recruits/show.html.erb
  app/views/resume_lists/show.html.erb
  public/403.html
Labels: 增加功能

#137 docs: README 更新
  README.md
Labels: 更新文檔

#139 Feat : S3 direct uploads + 音樂播放器增添色彩
  app/assets/stylesheets/application.css
  app/assets/stylesheets/direct_uploads.css
  app/javascript/application.js
  app/javascript/direct_uploads.js
  app/models/activity.rb
  app/views/activities/_form.html.erb
  app/views/bands/_form.html.erb
  app/views/bands/show.html.erb
  app/views/profiles/_form.html.erb
  app/views/profiles/show.html.erb
  config/environments/development.rb
Labels: 增加功能

#144 style: 修復 login 部分字顏色不會搭配亮暗色調調整。sweetalert2 404錯誤 移除
  app/controllers/activities_controller.rb
  app/controllers/api/v1/posts_controller.rb
  app/controllers/comments_controller.rb
  app/controllers/profiles_controller.rb
  app/helpers/devise_helper.rb
  app/models/activity.rb
  app/models/like_log.rb
  app/models/post.rb
  app/models/user.rb
  app/policies/activity_policy.rb
  app/policies/post_policy.rb
  app/policies/profile_policy.rb
  app/views/layouts/application.html.erb
  app/views/profiles/welcome.html.erb
  app/views/users/sessions/new.html.erb
  app/views/users/shared/_links.html.erb
Labels: bug, 急件先過！, 修正

#146 fix: like button fixed
  app/controllers/api/v1/posts_controller.rb
  app/controllers/posts_controller.rb
  app/javascript/controllers/like_controller.js
  app/views/posts/index.html.erb
Labels: bug, 修正

#143 fix: Data verification 資料驗證 + 修正頁面，比較有統一性
  app/assets/stylesheets/application.css
  app/assets/stylesheets/application.tailwind.css
  app/models/activity.rb
  app/models/band.rb
  app/models/band_member.rb
  app/models/profile.rb
  app/models/recruit.rb
  app/views/activities/_activity.html.erb
  app/views/activities/_form.html.erb
  app/views/activities/activity_index.html.erb
  app/views/activities/edit.html.erb
  app/views/activities/index.html.erb
  app/views/activities/new.html.erb
  app/views/activities/show.html.erb
  app/views/band_members/edit.html.erb
  app/views/bands/_band.html.erb
  app/views/bands/_form.html.erb
  app/views/bands/_recruit.html.erb
  app/views/bands/edit.html.erb
  app/views/bands/index.html.erb
  app/views/bands/new.html.erb
  app/views/bands/show.html.erb
  app/views/profiles/_form.html.erb
  app/views/profiles/_profile.html.erb
  app/views/profiles/edit.html.erb
  app/views/profiles/index.html.erb
  app/views/profiles/new.html.erb
  app/views/profiles/show.html.erb
  app/views/recruits/_form.html.erb
  app/views/recruits/edit.html.erb
  app/views/recruits/new.html.erb
  app/views/recruits/show.html.erb
  app/views/resume_lists/_form.html.erb
  app/views/resume_lists/new.html.erb
  config/locales/tw.yml
Labels: 修正

#148 feat: i18n 固定住，改成其他地區會自動跳回 tw
  app/controllers/application_controller.rb
Labels: 增加功能

#154 新增功能Notice
  Gemfile
  Gemfile.lock
  app/assets/images/icon/bell.svg
  app/controllers/application_controller.rb
  app/javascript/controllers/like_controller.js
  app/models/band.rb
  app/models/notification.rb
  app/models/resume_list.rb
  app/models/user.rb
  app/notifications/resume_list_notification.rb
  app/views/shared/_navbar.html.erb
  app/views/shared/_notification.html.erb
  app/views/shared/_notifications.html.erb
  config/locales/en.yml
  config/locales/tw.yml
  db/migrate/20230909140253_create_notifications.rb
  db/schema.rb
  test/fixtures/notifications.yml
  test/models/notification_test.rb
Labels: 增加功能

#155 hotfix: remove container from main
  app/views/layouts/application.html.erb
Labels: bug, 修正

#156 fix: profile index search CSS
  app/views/profiles/index.html.erb
Labels: bug, 修正

#157 Style: profile NEW 的 版面
  app/views/bands/edit.html.erb
  app/views/bands/new.html.erb
  app/views/profiles/new.html.erb
  db/schema.rb
Labels: bug, 修正

#158 fix: typo
  app/service/newebpay/mpg.rb
  db/seeds.rb
Labels: bug

#159 fix : profile finish fix + 其他發現的錯誤一併修改
  app/views/activities/activity_index.html.erb
  app/views/activities/show.html.erb
  app/views/profiles/_form.html.erb
  app/views/profiles/_profile.html.erb
  app/views/profiles/show.html.erb
  app/views/recruits/_form.html.erb
Labels: 修正

#162 fix: 修復沒有 profile 進討論區會壞掉的BUG, 另外補上 Demo前 兩個緊急沒推的 hotfix 進度
  app/service/newebpay/mpg.rb
  app/views/posts/_controls.html.erb
  app/views/posts/index.html.erb
  config/locales/en.yml
  config/locales/tw.yml
Labels: bug, 修正

#170 docs : some page descriptions 更新一些描述
  app/views/activities/_form.html.erb
  app/views/activities/edit.html.erb
  app/views/activities/index.html.erb
  app/views/activities/new.html.erb
  app/views/bands/edit.html.erb
  app/views/bands/new.html.erb
  app/views/bands/show.html.erb
  app/views/profiles/_form.html.erb
  app/views/profiles/letsjam.html.erb
  config/locales/tw.yml
Labels: 更新文檔

#173 style: 更改通知數量為紅點
  app/notifications/resume_list_notification.rb
  app/views/shared/_notifications.html.erb
Labels: 增加功能, 暫停與交回

#174 fix: 修正 devise 亂碼錯誤訊息, 並且改用 flash 顯示
  app/models/user.rb
  app/views/users/passwords/edit.html.erb
  app/views/users/registrations/edit.html.erb
  app/views/users/shared/_error_messages.html.erb
  config/locales/en.yml
  config/locales/tw.yml
Labels: bug, 修正

#179 feat: add notification light & dark
  app/assets/images/icon/bell.svg
  app/assets/stylesheets/application.css
  app/views/shared/_notifications.html.erb
Labels: 其他功能

#187 docs: post avatar set variant to resize
  app/helpers/posts_helper.rb
Labels: 修正

#191 fix:留言的控制器修正
  app/controllers/comments_controller.rb
Labels: bug, 修正

#189 Css adjust 3 修改 band profile search filter
  app/assets/stylesheets/application.css
  app/models/band.rb
  app/models/profile.rb
  app/views/band_members/_band_member.html.erb
  app/views/bands/show.html.erb
  app/views/profiles/_band.html.erb
  app/views/profiles/show.html.erb
  app/views/shared/_instrument.html.erb
  app/views/shared/_instrument_search.html.erb
  app/views/shared/_style_search.html.erb
  public/icon_img/主唱.svg
  public/icon_img/吉他.svg
  public/icon_img/吉他手.svg
  public/icon_img/爵士鼓.svg
  public/icon_img/貝斯.svg
  public/icon_img/貝斯手.svg
  public/icon_img/鍵盤.svg
  public/icon_img/鍵盤手.svg
  public/icon_img/鼓手.svg
Labels: 切版

#193 Feat: 點擊通知時, 消除通知
  app/controllers/bands_controller.rb
  app/controllers/resume_lists_controller.rb
  app/models/band.rb
  app/models/notification.rb
  app/models/profile.rb
  app/models/resume_list.rb
  app/models/user.rb
  app/notifications/resume_list_notification.rb
  app/policies/recruit_policy.rb
  app/views/recruits/show.html.erb
  app/views/resume_lists/show.html.erb
  app/views/shared/_notification.html.erb
  app/views/shared/_notifications.html.erb
  config/locales/en.yml
  config/locales/tw.yml
Labels: 增加功能, 急件先過！

#190 docs: set index video auto play on mobile
  app/views/pages/index.html.erb
Labels: 修正

#192 Refactor : footer 關於我們 + RWD
  app/controllers/pages_controller.rb
  app/views/pages/about.html.erb
  app/views/shared/_footer.html.erb
  config/routes.rb
  public/Joband_footer.svg
  public/github_footer.png
  public/hao.png
  public/heng.png
  public/james.png
  public/leo.png
  public/matt.png
  public/weber.png
Labels: 切版

#195 fix: update seed.rb
  db/seeds.rb
Labels: 更新文檔

#207 fix: notice & comment
  app/controllers/bands_controller.rb
  app/controllers/comments_controller.rb
Labels: bug, 修正

#208 fix:修正討論區活動顯示時間 並增加日期
  app/views/posts/index.html.erb
  db/schema.rb
Labels: 修正

#213 feat: add more i18n
  app/controllers/activities_controller.rb
  app/controllers/bands_controller.rb
  app/controllers/comments_controller.rb
  app/controllers/posts_controller.rb
  app/controllers/profiles_controller.rb
  app/controllers/recruits_controller.rb
  app/controllers/resume_lists_controller.rb
  app/views/activities/_form.html.erb
  app/views/activities/show.html.erb
  app/views/band_members/edit.html.erb
  app/views/bands/new.html.erb
  app/views/bands/show.html.erb
  app/views/channels/_controls.html.erb
  app/views/channels/_new.html.erb
  app/views/channels/_posts.html.erb
  app/views/channels/show.html.erb
  app/views/comments/_comment_activity.html.erb
  app/views/comments/_comment_post.html.erb
  app/views/comments/_comment_resume.html.erb
  app/views/posts/_controls.html.erb
  app/views/posts/_new.html.erb
  app/views/posts/_posts.html.erb
  app/views/posts/index.html.erb
  app/views/profiles/show.html.erb
  app/views/recruits/index.html.erb
  app/views/recruits/show.html.erb
  app/views/resume_lists/_form.html.erb
  app/views/resume_lists/show.html.erb
  config/locales/en.yml
  config/locales/tw.yml
Labels: 急件先過！, 修正

#212 Css adjust 5
  app/views/activities/_activity.html.erb
  app/views/bands/_band.html.erb
  app/views/bands/_form.html.erb
  app/views/channels/_new.html.erb
  app/views/posts/_new.html.erb
  app/views/posts/_posts.html.erb
  app/views/profiles/_form.html.erb
  app/views/profiles/_profile.html.erb
  app/views/profiles/show.html.erb
  app/views/shared/_footer.html.erb
  app/views/shared/_navbar.html.erb
  app/views/users/registrations/new.html.erb
  config/locales/en.yml
  config/locales/tw.yml
  db/seeds.rb
Labels: 切版

#216 docs: 開發模式 storage 換成 local，seed 加小註解
  app/views/shared/_footer.html.erb
  config/environments/development.rb
  db/seeds.rb
Labels: 更新文檔

#230 style: activities new edit CSS/RWD
  app/views/activities/_form.html.erb
  app/views/activities/edit.html.erb
  app/views/activities/new.html.erb
Labels: 切版

#232 fix: 修復 金流後會登出的問題，修復 第三方登入後回到 welcome
  app/controllers/orders_controller.rb
  app/controllers/users/omniauth_callbacks_controller.rb
  app/views/orders/paid_success.html.erb
  config/routes.rb
Labels: 修正

#234 style: paid CSS
  app/views/orders/paid_success.html.erb
  public/imges/bottle_beer.svg
Labels: 切版

#236 docs: close dropdown by click outside
  app/views/shared/_navbar.html.erb
Labels: 修正

#238 docs: fix post with long text
  app/views/posts/_posts.html.erb
  app/views/posts/index.html.erb
Labels: 修正

#239 style: refine profile new/edit CSS
  app/views/profiles/_form.html.erb
  config/locales/tw.yml
Labels: 切版

#240 style:修正post頁面留言太長會爆版以及按讚跑版問題
  app/views/comments/_comment_post.html.erb
  app/views/posts/_new.html.erb
  app/views/posts/index.html.erb
Labels: 切版, 修正
